// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq5Z-iMFcucJgeq8DqsY6VPDlP4DbV_48',
    appId: '1:407522119937:web:449d17be76cd9fc8cacb00',
    messagingSenderId: '407522119937',
    projectId: 'react-native-first-app-chat',
    authDomain: 'react-native-first-app-chat.firebaseapp.com',
    storageBucket: 'react-native-first-app-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ZspJA0JSmhhFgyn19nY7xineUfClX3Y',
    appId: '1:407522119937:android:bec4f5f12b48b6facacb00',
    messagingSenderId: '407522119937',
    projectId: 'react-native-first-app-chat',
    storageBucket: 'react-native-first-app-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE9MZzAOD4_CCxlvVpVleTgL4LsWPJkyQ',
    appId: '1:407522119937:ios:1a1d3789845aa4e9cacb00',
    messagingSenderId: '407522119937',
    projectId: 'react-native-first-app-chat',
    storageBucket: 'react-native-first-app-chat.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE9MZzAOD4_CCxlvVpVleTgL4LsWPJkyQ',
    appId: '1:407522119937:ios:5bdce4f706645ab9cacb00',
    messagingSenderId: '407522119937',
    projectId: 'react-native-first-app-chat',
    storageBucket: 'react-native-first-app-chat.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
